spring:
  threads:
    virtual:
      enabled: true
  cloud.gateway.mvc:
    routesMap:
      monoMartCatalogRoutes:
        uri: 'http://${INVENTORY_HOST:localhost:8081}'
        predicates:
          - Path=/api/catalogs/**
      monoMartProductRoutes:
        uri: 'http://${INVENTORY_HOST:localhost:8081}'
        predicates:
          - Path=/api/products/**
      monoMartCartRoutes:
        uri: 'http://${COMMERCE_HOST:localhost:8082}'
        predicates:
          - Path=/api/*/cart/**
      monoMartRoutes:
        uri: 'http://${MONOMART_HOST:localhost:8080}'
        predicates:
          - Path=/**

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'